services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sfm-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: sfm-redis
    restart: unless-stopped

  be-sfm:
    image: huynhtrongnhan98/sfm-backend:latest
    container_name: sfm-backend
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080

      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=SFM;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;"
      ConnectionStrings__Redis: "redis:6379"

      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}
      ACCESS_KEY_ID: ${ACCESS_KEY_ID}
      SECRET_ACCESS_KEY: ${SECRET_ACCESS_KEY}

      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      JWT_KEY: ${JWT_KEY}
      JWT_EXPIRE_MINUTES: ${JWT_EXPIRE_MINUTES}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}

    depends_on:
      - sqlserver
      - redis
    restart: unless-stopped

volumes:
  sqlserver_data: